services:
  db:
    image: postgres:16-alpine
    container_name: db-dev
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: supersecret_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  api:
    image: node:lts-alpine
    container_name: api-dev
    working_dir: /app
    command: sh -c "npm install && npm run db:migrate && npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: .
        target: /app
    environment:
      DATABASE_URL: postgres://appuser:supersecret_dev@db-dev:5432/appdb
      PORT: 3000
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata-dev:
